# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7ca580efbf4f73d82eb5fd7f07c9d1b21cfd48ce4c7fb2e73f2bcff9747870671461ce93de8a639b5c760fe5bc20957a2edcbb21cbe10da985299b1ce8e766
  admin_pass: pw

test:
  secret_key_base: 3f887a19198906199fdebb289000ac55791283441ef8e1adff526bcb88feaee5eb0d69e2213dc4356da6b042f80d0bf03c2ab658d73d6a74fb978422d68a0a69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
